- name: Sample code for printing Variables
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: "Please enter course:"
      private: false
    - name: DURATION
      prompt: "Please enter duration"
      private: false
    - name: TRAINER
      prompt: "Please enter trainer name"
      private: false
  tasks:
  - name: T01 Printing a sample message
    ansible.builtin.debug:
      msg: "Hi ..I m learning {{COURSE}} with duration {{DURATION}} at trainer {{TRAINER}}"